[package]
name = "searcher"
version = "0.1.0"
authors = ["Alex Rudy <opensource@alexrudy.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "*"
