[package]
name = "geometry"
version = "0.1.0"
authors = ["Alex Rudy <alex.rudy@gmail.com>"]
edition = "2018"

[dependencies]
thiserror = "*"
regex = "1"
lazy_static = "1"
itertools = "*"
searcher = { path = "../searcher" }
